#ifndef MEMORIZATION_GLOBAL_H
#define MEMORIZATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MEMORIZATION_EXTENSION)
#  define MEMORIZATION_EXPORT Q_DECL_EXPORT
#else
#  define MEMORIZATION_EXPORT Q_DECL_IMPORT
#endif


#endif // MEMORIZATION_GLOBAL_H
